name: Daily Commit Workflow

on:
  schedule:
    # Run daily at 12:00 PM UTC (adjust the cron syntax as needed)
    - cron: '0 12 * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add a commit (Step with your email gautamseyal2020@gmail.com)
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "gautamseyal2020@gmail.com"
          date > timestamp.txt
          git add timestamp.txt
          git commit -m "Daily automated commit"
          git push
